file <- read.csv("household_power_consumption.txt", sep = ";", colClasses = "character")
Date <- as.Date(file[, "Date"], format = "%d/%m/%Y") #Format to %Y-%m-%d
Time <- file[, "Time"]
DateTime <- paste(Date, Time)
TimeStamp <- strptime(DateTime, format = "%Y-%m-%d %H:%M:%S")
SubMetering1 <- as.numeric(file[, "Sub_metering_1"])
SubMetering2 <- as.numeric(file[, "Sub_metering_2"])
SubMetering3 <- as.numeric(file[, "Sub_metering_3"])
GlobalActivePower <- as.numeric(file[, "Global_active_power"])
Voltage <- as.numeric(file[, "Voltage"])
GlobalReactivePower <- as.numeric(file[, "Global_reactive_power"])
newtable <- data.frame(Date, TimeStamp, GlobalActivePower, SubMetering1, SubMetering2, SubMetering3, Voltage, GlobalReactivePower)
newtable.sub <- subset(newtable, Date >= "2007-02-01" & Date <= "2007-02-02", select = c(TimeStamp, GlobalActivePower, SubMetering1, SubMetering2, SubMetering3, Voltage, GlobalReactivePower))
yrange <- range(c(na.omit(newtable.sub[, "SubMetering1"]), na.omit(newtable.sub[, "SubMetering2"]), na.omit(newtable.sub[, "SubMetering1"])))
png(file = "plot4.png", width = 480, height = 480)
par(mfrow = c(2, 2))
with(newtable.sub, plot(TimeStamp, GlobalActivePower, main = "", pch = ".", type = "o", xlab = "", ylab = "Global Active Power (kilowatts)"))
with(newtable.sub, plot(TimeStamp, Voltage, main = "", pch = ".", type = "o", xlab = "datetime", ylab = "Voltage"))
with(newtable.sub, { plot(TimeStamp, SubMetering1, main = "", pch = ".", type = "o", xlab = "", ylab = "Energy sub metering", ylim = yrange)
                     par(new = T)
                     plot(TimeStamp, SubMetering2, axes = F, col = "red", main = "", pch = ".", type = "o", xlab = "", ylab = "", ylim = yrange)
                     par(new = T)
                     plot(TimeStamp, SubMetering3, axes = F, col = "blue", main = "", pch = ".", type = "o", xlab = "", ylab = "", ylim = yrange)
                     legend("topright", cex = 0.7, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1, 1, 1), xjust = 1)
                     
})
with(newtable.sub, plot(TimeStamp, GlobalActivePower, main = "", pch = ".", type = "o", xlab = "datetime", ylab = "Global_reactive_power"))
dev.off()

